// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Werkcollege05.Oef02.Data;

namespace Werkcollege05.Oef02.Migrations
{
    [DbContext(typeof(Werkcollege05Oef02Context))]
    partial class Werkcollege05Oef02ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Werkcollege05.Oef02.Models.Gebruiker", b =>
                {
                    b.Property<string>("Naam")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Wachtwoord");

                    b.HasKey("Naam");

                    b.ToTable("Gebruiker");
                });
#pragma warning restore 612, 618
        }
    }
}
